name: pathogd
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bbmap=38.96
  - bedtools=2.30.0
  - cd-hit=4.8.1
  - cdbtools=0.99
  - csvtk=0.25.0
  - emboss=6.6.0
  - genometester4=4.0
  - mafft=7.505
  - ncbi-genome-download=0.3.3
  - primer3=2.6.1  
  - prodigal=2.6.3
  - python=3.10
  - samtools=1.6
  - seqkit=2.3.1
  - taxonkit=0.15.0
  - wget

  - r-base=4.2.0
  - r-cli=3.3.0
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-data.table=1.14.2
  - r-dplyr=1.0.9
  - r-ellipsis=0.3.2
  - r-fansi=1.0.3
  - r-generics=0.1.3
  - r-glue=1.6.2
  - r-lifecycle=1.0.1
  - r-magrittr=2.0.3
  - r-pillar=1.8.1
  - r-pkgconfig=2.0.3
  - r-purrr=0.3.4
  - r-r6=2.5.1
  - r-rlang=1.0.2
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-tibble=3.1.7
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.2
  - r-utf8=1.2.2
  - r-vctrs=0.4.1